repos:
-   repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
    -   id: black
          language_version: python3
    -   id: blacken-docs
          language_version: python3

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: debug statements (python)
          language_version: python3

-   repo: repo: https://gitlab.com/pycqa/flake8.git
    rev: 3.7.9
    hooks:
    -   id: flake8
          language_version: python3
          additional_dependencies:
          - flake8-black>=0.1.1
    -   id: re-order python imports
          language_version: python3
    -   id: pyupgrade
        language_version: python3