[pytest]

markers = 
    unit: tests that are isolated from the db, external api calls and other mockable internal code.
python_files = test_*.py
addopts = --ff --no-migrations -vv -x --lf 
env_files =
    .env